[package]
name = "cloudflare"
version = "0.1.0"
authors = ["Mackenzie Hauck <mhauck@live.ca>"]

[dependencies]
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0" 
url = "1.6"
serde_json = "1.0"
hyper = "0.11"

[dev-dependencies]
dotenv = "0.11"
lazy_static = "1.0"